### ISSUE TITLE
세미콜론이슈 이런 케이스도 있어요

### ISSUE THREAD

**Issue by yunjunseokzb** [zigbang/zigbang-config#7]
const a = 1
const b = 2
const c = a + b
(a + b).toString()

**Comment by xeoh** [comment]
[tslint-plugin-prettier](https://github.com/prettier/tslint-plugin-prettier)로 semicolon이슈는 해결하였습니다. 앞으로 이슈있어보이면 언제든지 이슈달아주세요!
